import { ArrowLeft, ArrowUpRight } from "lucide-react"
import type { ReactNode } from "react"
import { BrandHeader, PublicFooter } from "@/components/product/shell"
import { useProduct } from "@/lib/product-context"
import { sitePath } from "@/lib/utils"

const contact = "senturkberkin@gmail.com"

function LegalFrame({ kind, children }: { kind: "privacy" | "terms"; children: ReactNode }) {
  const { tx } = useProduct()
  const isPrivacy = kind === "privacy"
  return <div className="min-h-screen bg-background text-foreground">
    <BrandHeader mode="app" />
    <main className="mx-auto max-w-[900px] px-5 pb-24 pt-10 sm:px-8 sm:pt-16">
      <a href={sitePath("/")} className="inline-flex items-center gap-2 text-[13px] font-medium text-primary hover:underline"><ArrowLeft className="size-4" />{tx("Back to home", "Ana sayfaya dön")}</a>
      <div className="mt-10 max-w-[720px]"><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-primary">Hearthline / {tx("Legal", "Yasal")}</p><h1 className="mt-3 text-[clamp(2.5rem,5vw,4rem)] font-semibold leading-[1.05] tracking-[-.06em]">{isPrivacy ? tx("Privacy", "Gizlilik") : tx("Terms of use", "Kullanım koşulları")}</h1><p className="mt-4 text-[14px] text-ink-soft">{tx("Updated October 1, 2026", "Güncelleme: 1 Ekim 2026")} · Berkin Senturk</p></div>
      <div className="mt-10 rounded-[20px] bg-[#edf2ff] p-6 sm:p-8">{isPrivacy ? <><strong className="text-[17px] font-semibold">{tx("Your scenario stays in your browser.", "Senaryon tarayıcında kalır.")}</strong><p className="mt-2 max-w-[670px] text-[14px] leading-6 text-ink-soft">{tx("Hearthline has no account, advertising tracker or analytics script. GitHub Pages hosts the site and may process visit data for security.", "Hearthline'da hesap, reklam takibi veya analiz betiği yoktur. Siteyi barındıran GitHub Pages, ziyaret verilerini güvenlik amacıyla işleyebilir.")}</p></> : <><strong className="text-[17px] font-semibold">{tx("A planning aid, not a recommendation.", "Karar desteği, tavsiye değil.")}</strong><p className="mt-2 max-w-[670px] text-[14px] leading-6 text-ink-soft">{tx("The result follows the assumptions you enter. It does not predict prices, income, rent or interest rates.", "Sonuç, girdiğin varsayımlara dayanır. Ev fiyatını, gelirini, kirayı veya faiz oranlarını tahmin etmez.")}</p></>}</div>
      <div className="mt-12 space-y-10 text-[14px] leading-7 text-ink-soft [&_h2]:mb-3 [&_h2]:text-[20px] [&_h2]:font-semibold [&_h2]:tracking-[-.03em] [&_h2]:text-foreground [&_a]:font-medium [&_a]:text-primary [&_a]:underline-offset-4 hover:[&_a]:underline">{children}</div>
    </main>
    <PublicFooter />
  </div>
}

export function PrivacyPage() {
  const { tx } = useProduct()
  return <LegalFrame kind="privacy">
    <section><h2>{tx("Who operates Hearthline?", "Hearthline'ı kim işletiyor?")}</h2><p>{tx("Hearthline is operated by Berkin Senturk. For privacy questions or requests, write to", "Hearthline, Berkin Senturk tarafından işletilir. Gizlilikle ilgili soru ve talepler için yazabilirsin:")} <a href={`mailto:${contact}`}>{contact}</a>.</p></section>
    <section><h2>{tx("What stays in your browser?", "Tarayıcında neler saklanır?")}</h2><p>{tx("Income, rent, home price and other scenario inputs are calculated in your browser and saved in session storage so the setup and results pages can share them. Language, theme and the dated rent reference are saved in local storage. These values are not sent to a Hearthline account or database. You can remove them through your browser's site-data settings; the Results page's Clear data control resets your scenario.", "Gelir, kira, ev fiyatı ve diğer senaryo girdileri tarayıcında hesaplanır. Kurulum ve sonuç sayfaları arasında kullanılabilmeleri için oturum depolamasında saklanırlar. Dil, tema ve tarihli kira referansı yerel depolamada tutulur. Bu bilgiler bir Hearthline hesabına veya veri tabanına gönderilmez. Tarayıcının site verileri ayarlarından silebilir; Sonuçlar sayfasındaki Verileri temizle seçeneğiyle senaryonu sıfırlayabilirsin.")}</p></section>
    <section><h2>{tx("Hosting and outside services", "Barındırma ve dış hizmetler")}</h2><p>{tx("GitHub Pages serves this website. GitHub says it logs visitors' IP addresses for security, even when they are not signed in. Hearthline itself does not include advertising or analytics scripts, and does not set tracking cookies. Its fonts are served with the site. If you open the official TÜİK source link, you leave Hearthline and that site's own privacy practices apply.", "Bu site GitHub Pages üzerinden sunulur. GitHub, oturum açmamış ziyaretçiler dahil IP adreslerini güvenlik amacıyla kaydettiğini belirtir. Hearthline'ın kendi reklam veya analiz betiği ve takip çerezi yoktur; yazı tipleri de siteyle birlikte sunulur. Resmî TÜİK kaynak bağlantısını açarsan Hearthline'dan ayrılırsın ve o sitenin gizlilik uygulamaları geçerli olur.")}</p><p className="mt-3"><a href="https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages" target="_blank" rel="noopener noreferrer">{tx("GitHub Pages data collection", "GitHub Pages veri toplama açıklaması")} <ArrowUpRight className="inline size-3" /></a> · <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noopener noreferrer">{tx("GitHub privacy statement", "GitHub gizlilik bildirimi")} <ArrowUpRight className="inline size-3" /></a></p></section>
    <section><h2>{tx("If you email us", "E-posta gönderirsen")}</h2><p>{tx("If you contact Berkin Senturk, your email address and message are used to respond to your request and to meet any applicable legal obligations. Please do not include sensitive financial details unless necessary. Your email provider and the recipient's email provider handle that correspondence under their own terms.", "Berkin Senturk'e e-posta gönderirsen adresin ve mesajın, talebini yanıtlamak ve varsa yasal yükümlülükleri yerine getirmek için kullanılır. Gerekmedikçe hassas finansal bilgilerini e-postana ekleme. Yazışma, senin ve alıcının e-posta sağlayıcılarının koşullarına da tabidir.")}</p></section>
    <section><h2>{tx("Your choices and requests", "Tercihlerin ve taleplerin")}</h2><p>{tx("You can change language and theme in the site controls, reset your scenario, or clear this site's browser storage. For access, correction, deletion or other personal-data requests under applicable law, contact", "Dil ve tema tercihini siteden değiştirebilir, senaryonu sıfırlayabilir veya tarayıcıdaki site verilerini silebilirsin. Uygulanabilir hukuk kapsamındaki bilgi alma, düzeltme, silme ve diğer kişisel veri taleplerin için iletişime geçebilirsin:")} <a href={`mailto:${contact}`}>{contact}</a>. <a href="https://www.kvkk.gov.tr/Icerik/2033/Aydinlatma-Yukumlulugu-" target="_blank" rel="noopener noreferrer">{tx("KVKK information", "KVKK bilgilendirmesi")} <ArrowUpRight className="inline size-3" /></a>.</p></section>
    <section><h2>{tx("Changes", "Değişiklikler")}</h2><p>{tx("This page may change if the product or its service providers change. The update date above shows the current version.", "Ürün veya hizmet sağlayıcıları değişirse bu sayfa güncellenebilir. Üstteki tarih güncel sürümü gösterir.")}</p></section>
  </LegalFrame>
}

export function TermsPage() {
  const { tx } = useProduct()
  return <LegalFrame kind="terms">
    <section><h2>{tx("The service", "Hizmet")}</h2><p>{tx("Hearthline, operated by Berkin Senturk, is a free, educational rent-versus-buy scenario simulator. It does not offer a mortgage, broker a loan, sell a financial product or create a user account.", "Berkin Senturk tarafından işletilen Hearthline, ücretsiz ve eğitim amaçlı bir kira–ev alma senaryo aracıdır. Kredi sunmaz, kredi aracılığı yapmaz, finansal ürün satmaz veya kullanıcı hesabı oluşturmaz.")}</p></section>
    <section><h2>{tx("Your assumptions and decisions", "Varsayımların ve kararların")}</h2><p>{tx("Results are illustrations calculated from the numbers you enter and the model's stated assumptions. They are not market forecasts or personalized financial, legal, tax or mortgage advice. Check actual loan terms, costs and current rules independently before making a housing decision. You remain responsible for your inputs and decisions.", "Sonuçlar, girdiğin rakamlar ve modelde belirtilen varsayımlar üzerinden hesaplanan örneklerdir. Piyasa tahmini veya kişiye özel finans, hukuk, vergi ya da kredi tavsiyesi değildir. Konut kararı vermeden önce gerçek kredi koşullarını, giderleri ve güncel kuralları bağımsız olarak doğrula. Girdilerinden ve kararlarından sen sorumlusun.")}</p></section>
    <section><h2>{tx("References and third-party links", "Referanslar ve dış bağlantılar")}</h2><p>{tx("A dated TÜİK rent reference may be shown for context but is not applied automatically. External websites, including TÜİK and GitHub, have their own content, terms and privacy practices. Their inclusion is not an endorsement or a guarantee that information remains current.", "Tarihli TÜİK kira referansı bağlam sağlamak için gösterilebilir; hesaplamaya kendiliğinden uygulanmaz. TÜİK ve GitHub dahil dış sitelerin içerikleri, koşulları ve gizlilik uygulamaları kendilerine aittir. Bağlantı verilmesi, bilgilerin güncel olduğuna dair garanti veya onay anlamına gelmez.")}</p></section>
    <section><h2>{tx("Availability and changes", "Erişim ve değişiklikler")}</h2><p>{tx("The site is provided as available. Features and these terms may change. To the extent permitted by applicable law, no guarantee is made that the site will always be uninterrupted or error-free. Changes to these terms will be reflected in the update date above.", "Site mevcut hâliyle sunulur. Özellikler ve bu koşullar değişebilir. Uygulanabilir hukukun izin verdiği ölçüde sitenin her zaman kesintisiz veya hatasız çalışacağı garanti edilmez. Koşullardaki değişiklikler üstteki güncelleme tarihine yansıtılır.")}</p></section>
    <section><h2>{tx("Content and software", "İçerik ve yazılım")}</h2><p>{tx("Hearthline's original content and visual identity belong to Berkin Senturk. The website uses third-party open-source software subject to its own licenses. Public access to the source repository does not by itself grant additional rights to its original content.", "Hearthline'ın özgün içeriği ve görsel kimliği Berkin Senturk'e aittir. Sitede kendi lisanslarına tabi üçüncü taraf açık kaynak yazılımlar kullanılır. Kaynak deponun herkese açık olması, özgün içerik için kendiliğinden ek kullanım hakkı vermez.")}</p></section>
    <section><h2>{tx("Contact", "İletişim")}</h2><p>{tx("Questions about these terms can be sent to", "Bu koşullarla ilgili sorularını iletebilirsin:")} <a href={`mailto:${contact}`}>{contact}</a>.</p></section>
  </LegalFrame>
}
